version: '2'
services:
  jod:
    image: guilhermeadc/sei3_jod-2.2.2:8.0
    container_name: jod
    ports:
      - "8080:8080"

  smtp:
      image: guilhermeadc/sei3_mailcatcher:8.0
      container_name: smtp
      ports:
        - "1080:1080"

  memcached:
    image: guilhermeadc/sei3_memcached:8.0
    container_name: memcached
    ports:
      - "11211:11211"

 sqlserver:
   image: guilhermeadc/sei3_sqlserver-2017:8.0
   container_name: sqlserver
   ports:
     - "1433:1433"

  solr:
    image: guilhermeadc/sei3_solr-6.1:8.0
    container_name: solr
    ports:
      - "8983:8983"

  http:
    image: guilhermeadc/sei3_httpd-2.4
    container_name: httpd
    ports:
      - "80:80"
    volumes:
      - /mnt/sei/src:/opt
    environment:
      - XDEBUG_CONFIG="idekey=default remote_enable=1 remote_mode=req remote_port=9000 remote_host=10.0.2.2 remote_connect_back=1"
      - SEI_HOST_URL=http://localhost      
      - SEI_DATABASE_NAME=sei
      - SEI_DATABASE_USER=sei_user
      - SEI_DATABASE_PASSWORD=sei_user
      - SIP_DATABASE_NAME=sip
      - SIP_DATABASE_USER=sip_user
      - SIP_DATABASE_PASSWORD=sip_user
    links:
      - sqlserver:sqlserver
      - memcached:memcached
      - solr:solr
      - smtp:smtp
      - jod:jod
