version: '2'
services:
  jod:  
    image: guilhermeadc/sei4_jod:${ENVIRONMENT_VERSION}
    build: ./jod/
    container_name: jod

  smtp:
    image: guilhermeadc/sei4_mailcatcher:${ENVIRONMENT_VERSION}
    build: ./mailcatcher/
    container_name: smtp
    ports:
      - "1080:1080"

  memcached:
    image: guilhermeadc/sei4_memcached:${ENVIRONMENT_VERSION}
    build: ./memcached/
    container_name: memcached
    ports:
      - "11211:11211"

  database:
    image: ${DATABASE_IMAGE}:${ENVIRONMENT_VERSION}
    build: ./mysql/
    container_name: ${DATABASE_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${DATABASE_HOST}:${DATABASE_DATA_DIR}
      - /var/sei/${DATABASE_HOST}/backup:/backup
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  solr:
    image: guilhermeadc/sei4_solr:${ENVIRONMENT_VERSION}
    build: ./solr/
    container_name: solr
    ports:
      - "8983:8983"

  http:
    image: guilhermeadc/sei4_httpd:${ENVIRONMENT_VERSION}
    container_name: http
    build: ./httpd/
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - database
    privileged: true
    volumes:
#      - /mnt/sei/src:/opt:
      - C:\Projetos\SEI\SEI_v4.0_Oficial\fontes\sei\src\main\php:/opt
    environment:
      - XDEBUG_CONFIG="idekey=default remote_enable=1 remote_mode=req remote_port=9000 remote_host=172.22.32.1yu remote_connect_back=1"
      - HOST_URL=http://localhost:8000
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - SEI_DATABASE_USER_SCRIPT=${SEI_DATABASE_USER_SCRIPT}
      - SEI_DATABASE_PASSWORD_SCRIPT=${SEI_DATABASE_PASSWORD_SCRIPT}
      
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
      - SIP_DATABASE_USER_SCRIPT=${SIP_DATABASE_USER_SCRIPT}
      - SIP_DATABASE_PASSWORD_SCRIPT=${SIP_DATABASE_PASSWORD_SCRIPT}
    links:
      - database:${DATABASE_HOST}
      - memcached:memcached
      - solr:solr
      - smtp:smtp
      - jod:jod


volumes:
  mysql:
  oracle:
  sqlserver:
